// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-blog/internal/biz"
	"kratos-blog/internal/conf"
	"kratos-blog/internal/data"
	"kratos-blog/internal/server"
	"kratos-blog/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	authUseCase := biz.NewAuthUseCase(auth, userRepo)
	userUseCase := biz.NewUserUseCase(userRepo, logger, authUseCase)
	blogService := service.NewBlogService(articleUsecase, userUseCase, authUseCase, logger)
	authService := service.NewAuthService()
	httpServer := server.NewHTTPServer(confServer, auth, blogService, authService, logger)
	grpcServer := server.NewGRPCServer(confServer, blogService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
