version: '3'
services:
  blog-db:
    image: mysql:8
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kratos-blog # for database creation automatically
      # MYSQL_USER: 'blog'
      # MYSQL_PASS: '123456'
      # volumes:
      #   - ./data:/var/lib/mysql
      #   - ./config/my.cnf:/etc/my.cnf
      #   - ./init:/docker-entrypoint-initdb.d/
      # command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     mysql -u root -p
      #     123456
      #     ALTER USER 'root'@'%' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
      #     ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '123456';
      #     FLUSH PRIVILEGES;
    ports:
      - 3306:3306
    # volumes:
    #   - "./data:/var/lib/mysql"
  blog-redis:
    image: redis:latest
    container_name: blog-redis
    restart: always
    ports:
      - 6379:6379
    # networks:
    #   - mynetwork
    # volumes:
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
    #   - ./data:/data:rw
    # command:
    #   /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "

